/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_netease_mm_segment_jni_ImageSegment */

#ifndef _Included_com_netease_mm_segment_jni_ImageSegment
#define _Included_com_netease_mm_segment_jni_ImageSegment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_netease_mm_segment_jni_ImageSegment
 * Method:    segment
 * Signature: ([BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_netease_mm_segment_jni_ImageSegment_segment
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
